/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.taqque.iu;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.taqque.almacenamiento.Atributo;
import org.taqque.almacenamiento.Catalogo;
import org.taqque.almacenamiento.EntradaCatalogo;
import org.taqque.almacenamiento.GestorAlmacenamiento;
import org.taqque.almacenamiento.GestorIORelacion;
import org.taqque.almacenamiento.Tabla;
import org.taqque.almacenamiento.Tupla;
import org.taqque.memoriaintermedia.GestorMemoriaIntermedia;

/**
 *
 * @author Usuario38
 */
public class AbrirTablaIU extends javax.swing.JFrame {

    private GestorAlmacenamiento gestorAlmacenamiento;
    private GestorMemoriaIntermedia gestorMemoriaIntermedia;
    private GestorIORelacion gestorIORelacion;
    private TuplasTableModel tuplasTableModel;
    private Catalogo catalogo;
    private EntradaCatalogo entrada;

    /**
     * Creates new form AbrirTablaIU
     */
    public AbrirTablaIU(Catalogo catalogo, EntradaCatalogo entrada) {
        initComponents();
        this.catalogo = catalogo;
        this.entrada = entrada;
        gestorMemoriaIntermedia = new GestorMemoriaIntermedia(2);
        gestorAlmacenamiento =
                new GestorAlmacenamiento(catalogo, gestorMemoriaIntermedia);
        gestorIORelacion =
                new GestorIORelacion(gestorAlmacenamiento,
                entrada.getTabla(),
                entrada.getNombreArchivo());
        // this.gestorAlmacenamiento.crearArchivo(entrada.getNombreArchivo());

        tuplasTableModel = new TuplasTableModel(arregloColumnas(entrada));
        tablaTuplas.setModel(tuplasTableModel);


    }

    private ArrayList<String> arregloColumnas(EntradaCatalogo entrada) {
        Iterator<Atributo> it = entrada.getTabla().iterator();
        ArrayList<String> columnas = new ArrayList<String>();
        while (it.hasNext()) {
            columnas.add(it.next().getNombre());
        }
        return columnas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTuplas = new javax.swing.JTable();
        btnNuevaTupla = new javax.swing.JButton();
        btnGuardarTablas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaTuplas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaTuplas);

        btnNuevaTupla.setText("Nueva Tupla");
        btnNuevaTupla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaTuplaActionPerformed(evt);
            }
        });

        btnGuardarTablas.setText("Guardar datos");
        btnGuardarTablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTablasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardarTablas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNuevaTupla, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevaTupla)
                    .addComponent(btnGuardarTablas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaTuplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaTuplaActionPerformed
        // TODO add your handling code here:

        Tupla tupla = new Tupla();
        List<Comparable> valores = new ArrayList<Comparable>();
        Iterator<Atributo> it = entrada.getTabla().iterator();
        while (it.hasNext()) {
            Atributo atributo = it.next();
            if (atributo.getTipo().equals(String.class))
                valores.add(new String());
            if (atributo.getTipo().equals(Integer.class))
                valores.add(new Integer(0));
            if (atributo.getTipo().equals(Float.class))
                valores.add(new Float(0f));
            if (atributo.getTipo().equals(Double.class))
                valores.add(new Double(0d));
        }
        tupla.setValores(valores);
        tuplasTableModel.addRow(tupla);
        
    }//GEN-LAST:event_btnNuevaTuplaActionPerformed

    private void btnGuardarTablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTablasActionPerformed
        // TODO add your handling code here:
           GestorMemoriaIntermedia 
                   gmi = new GestorMemoriaIntermedia(2);
           GestorAlmacenamiento ga = 
                   new GestorAlmacenamiento(catalogo, gmi);
           
           ga.crearArchivo(entrada.getNombreArchivo());
           
           GestorIORelacion gestor =
                   new GestorIORelacion(ga, entrada.getTabla(), entrada.getNombreArchivo());
        for (Tupla tupla : tuplasTableModel.getListaTuplas()) {
            gestor.insertarTupla(tupla.getValores());
        }
    }//GEN-LAST:event_btnGuardarTablasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbrirTablaIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbrirTablaIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbrirTablaIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbrirTablaIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AbrirTablaIU(null, null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarTablas;
    private javax.swing.JButton btnNuevaTupla;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaTuplas;
    // End of variables declaration//GEN-END:variables
}
