/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.taqque.iu;

import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.table.TableColumn;
import org.taqque.almacenamiento.Atributo;
import org.taqque.almacenamiento.Catalogo;
import org.taqque.almacenamiento.EntradaCatalogo;
import org.taqque.almacenamiento.Tabla;

/**
 *
 * @author Usuario38
 */
public class BaseDatosIU extends javax.swing.JFrame {

    private Catalogo catalogo;
    private DefaultListModel modeloLista = new DefaultListModel();
    private AtributoTableModel modeloTabla = new AtributoTableModel();
    private JComboBox cboTipo = new JComboBox();

    /**
     * Creates new form BaseDatosIU
     */
    public BaseDatosIU(Catalogo catalogo) {
        initComponents();
        this.catalogo = catalogo;
        mostrarInformacionCatalogo();
        this.tablaInfoTabla.setModel(modeloTabla);
        llenarTipos();
        TableColumn tipoColumn = tablaInfoTabla.getColumnModel().getColumn(1);
        tipoColumn.setCellEditor(new DefaultCellEditor(cboTipo));
    }
    
    private void llenarTipos()
    {
        cboTipo.addItem(String.class);
        cboTipo.addItem(Integer.class);
        cboTipo.addItem(Float.class);
        cboTipo.addItem(Double.class);
        cboTipo.addItem(Character.class);
        cboTipo.addItem(Boolean.class);
        cboTipo.addItem(Long.class);
    }

    private void mostrarInformacionCatalogo() {
        this.txtNombreBD.setText(catalogo.getPath());
        modeloLista.clear();
        Collection<EntradaCatalogo> lista = catalogo.getEntradas().values();
        for (EntradaCatalogo entrada : lista) {
            modeloLista.addElement(entrada);
        }
        lstListaTablas.setModel(modeloLista);
    }

    private void informacionTabla(EntradaCatalogo entrada) {
        modeloTabla.limpiarModeloTabla();
        Iterator<Atributo> iterator = entrada.getTabla().iterator();
        while (iterator.hasNext()) {
            Atributo atributo = iterator.next();
            modeloTabla.addRow(atributo);
        }
        tablaInfoTabla.setModel(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombreBD = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstListaTablas = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaInfoTabla = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreTabla = new javax.swing.JTextField();
        btnNuevaTabla = new javax.swing.JButton();
        btnGuardarTabla = new javax.swing.JButton();
        btnNuevoAtributo = new javax.swing.JButton();
        btnEliminarTabla = new javax.swing.JButton();
        btnAbrirTabla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre de BD:");

        lstListaTablas.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstListaTablas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstListaTablasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstListaTablas);

        jLabel2.setText("Lista de tablas:");

        tablaInfoTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaInfoTabla);

        jLabel3.setText("Información de tabla");

        jLabel4.setText("Nombre tabla:");

        btnNuevaTabla.setText("Nueva Tabla");
        btnNuevaTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaTablaActionPerformed(evt);
            }
        });

        btnGuardarTabla.setText("Guardar Tabla");
        btnGuardarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTablaActionPerformed(evt);
            }
        });

        btnNuevoAtributo.setText("Nuevo Atributo");
        btnNuevoAtributo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoAtributoActionPerformed(evt);
            }
        });

        btnEliminarTabla.setText("Eliminar tabla");
        btnEliminarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTablaActionPerformed(evt);
            }
        });

        btnAbrirTabla.setText("Abrir tabla");
        btnAbrirTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirTablaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(txtNombreBD))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnEliminarTabla)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAbrirTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(309, 309, 309)
                                        .addComponent(btnNuevoAtributo))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnNuevaTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4)
                                        .addGap(26, 26, 26)
                                        .addComponent(txtNombreTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardarTabla)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(btnNuevoAtributo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombreTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevaTabla)
                    .addComponent(btnEliminarTabla)
                    .addComponent(btnAbrirTabla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardarTabla)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstListaTablasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstListaTablasMouseClicked
        // TODO add your handling code here:
        int idx = this.lstListaTablas.getSelectedIndex();
        EntradaCatalogo entrada = (EntradaCatalogo) modeloLista.get(idx);
        this.txtNombreTabla.setText(entrada.getNombreTabla());
        informacionTabla(entrada);
    }//GEN-LAST:event_lstListaTablasMouseClicked

    private void btnNuevaTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaTablaActionPerformed
        // TODO add your handling code here:
        this.modeloTabla.limpiarModeloTabla();
        this.txtNombreTabla.setText("");
    }//GEN-LAST:event_btnNuevaTablaActionPerformed

    private void btnNuevoAtributoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoAtributoActionPerformed
        // TODO add your handling code here:
        Atributo atributo = new Atributo("atributo", String.class);
        modeloTabla.addRow(atributo);
    }//GEN-LAST:event_btnNuevoAtributoActionPerformed

    private void btnGuardarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTablaActionPerformed
        // TODO add your handling code here:
        List<Atributo> lista = modeloTabla.getListaAtributos();
        Tabla tabla = new Tabla(this.txtNombreTabla.getText(),
                lista);
        EntradaCatalogo entrada =
                new EntradaCatalogo(tabla, catalogo.getDirectorio());
        catalogo.crearNuevaEntrada(entrada);
        actualizarCatalogo();

    }//GEN-LAST:event_btnGuardarTablaActionPerformed

    private void btnEliminarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTablaActionPerformed
        // TODO add your handling code here:
        int idx = this.lstListaTablas.getSelectedIndex();
        EntradaCatalogo entrada = (EntradaCatalogo) modeloLista.get(idx);
        catalogo.eliminarTabla(entrada.getNombreTabla());
        actualizarCatalogo();
    }//GEN-LAST:event_btnEliminarTablaActionPerformed

    private void btnAbrirTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirTablaActionPerformed
        // TODO add your handling code here:
        int idx = this.lstListaTablas.getSelectedIndex();
        EntradaCatalogo entrada = (EntradaCatalogo) modeloLista.get(idx);
        
        AbrirTablaIU abrirTablaIU = new AbrirTablaIU(catalogo,entrada);
        abrirTablaIU.setVisible(true);
    }//GEN-LAST:event_btnAbrirTablaActionPerformed

    private void actualizarCatalogo() {
        try {
            catalogo.escribirCatalogo();
            catalogo.leerCatalogo();
            modeloTabla.limpiarModeloTabla();
            this.mostrarInformacionCatalogo();
            this.txtNombreTabla.setText("");
        } catch (Exception ex) {
            Logger.getLogger(BaseDatosIU.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaseDatosIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaseDatosIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaseDatosIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaseDatosIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaseDatosIU(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirTabla;
    private javax.swing.JButton btnEliminarTabla;
    private javax.swing.JButton btnGuardarTabla;
    private javax.swing.JButton btnNuevaTabla;
    private javax.swing.JButton btnNuevoAtributo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lstListaTablas;
    private javax.swing.JTable tablaInfoTabla;
    private javax.swing.JTextField txtNombreBD;
    private javax.swing.JTextField txtNombreTabla;
    // End of variables declaration//GEN-END:variables

}
