/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.taqque.iu;

import java.io.File;
import java.util.Collection;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.taqque.almacenamiento.Catalogo;
import org.taqque.almacenamiento.EntradaCatalogo;
import org.taqque.almacenamiento.Tabla;

/**
 *
 * @author Usuario38
 */
public class TaqqueIU extends javax.swing.JFrame {
    
    private Catalogo catalogo;
    /**
     * Creates new form TaqqueIU
     */
    public TaqqueIU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCrearBD = new javax.swing.JMenuItem();
        jMenuItemAbrirBD = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Archivo");

        jMenuItemCrearBD.setText("Crear base de datos");
        jMenuItemCrearBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearBDActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCrearBD);

        jMenuItemAbrirBD.setText("Abrir base de datos");
        jMenuItemAbrirBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAbrirBDActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAbrirBD);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 354, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAbrirBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAbrirBDActionPerformed
        // TODO add your handling code here:
        javax.swing.JFileChooser dialogo = new javax.swing.JFileChooser();
        if (dialogo.showOpenDialog(this)== JFileChooser.APPROVE_OPTION)
        {
            File archivo = dialogo.getSelectedFile();
            File directorio = dialogo.getCurrentDirectory();
            catalogo = new Catalogo(directorio.getAbsolutePath(),
                    archivo.getName());
            try {
                catalogo.leerCatalogo();
            } catch (Exception ex) {
                Logger.getLogger(TaqqueIU.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        BaseDatosIU baseDatosIU = new BaseDatosIU(catalogo);
        baseDatosIU.setVisible(true);
    }//GEN-LAST:event_jMenuItemAbrirBDActionPerformed

    private void jMenuItemCrearBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearBDActionPerformed
        // TODO add your handling code here:
        javax.swing.JFileChooser dialogo = new javax.swing.JFileChooser();
        if (dialogo.showSaveDialog(this)== JFileChooser.APPROVE_OPTION)
        {
            File archivo = dialogo.getSelectedFile();
            File directorio = dialogo.getCurrentDirectory();
            catalogo = new Catalogo(directorio.getAbsolutePath(),
                    archivo.getName());
            try {
                catalogo.escribirCatalogo();
                catalogo.leerCatalogo();
            } catch (Exception ex) {
                Logger.getLogger(TaqqueIU.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        BaseDatosIU baseDatosIU = new BaseDatosIU(catalogo);
        baseDatosIU.setVisible(true);
    }//GEN-LAST:event_jMenuItemCrearBDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaqqueIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaqqueIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaqqueIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaqqueIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaqqueIU().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAbrirBD;
    private javax.swing.JMenuItem jMenuItemCrearBD;
    // End of variables declaration//GEN-END:variables
}
